import React, { useState } from 'react';
import { useQA } from '../contexts/QAContext';
import AnswerDisplay from '../components/AnswerDisplay';
import QAHistory from '../components/QAHistory';
import './BibleQAPage.css';

const BibleQAPage = () => {
  const { askQuestion, loading, error, history } = useQA();
  const [question, setQuestion] = useState('');
  const [currentAnswer, setCurrentAnswer] = useState(null);
  const [showHistory, setShowHistory] = useState(false);

  const exampleQuestions = [
    "Where does the Bible talk about forgiveness?",
    "What does the Bible say about prayer?",
    "What is the main theme of the book of Romans?",
    "How can I show love to others according to the Bible?",
    "What does the Bible teach about faith?"
  ];

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!question.trim()) {
      return;
    }

    try {
      const answer = await askQuestion(question.trim());
      setCurrentAnswer(answer);
      setQuestion(''); // Clear input after successful submission
    } catch (err) {
      // Error is handled by context
      console.error('Error submitting question:', err);
    }
  };

  const handleExampleClick = (exampleQuestion) => {
    setQuestion(exampleQuestion);
  };

  const handleFollowUpClick = (followUpQuestion) => {
    setQuestion(followUpQuestion);
    setCurrentAnswer(null);
    // Scroll to top
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div className="bible-qa-page">
      <div className="qa-container">
        <header className="qa-header">
          <h1>Ask About the Bible</h1>
          <p className="qa-subtitle">
            Get AI-powered answers to your Bible questions with scripture references
          </p>

          {/* Safety Disclaimer */}
          <div className="qa-disclaimer">
            <span className="disclaimer-icon">ℹ️</span>
            <p>
              <strong>AI-Assisted Guidance:</strong> These answers are generated by AI and are meant
              to assist your Bible study. They are not a substitute for pastoral counsel, prayer,
              or personal study. Always verify answers with scripture and discuss complex topics
              with your youth leaders or pastors.
            </p>
          </div>
        </header>

        {/* Question Input Form */}
        <form onSubmit={handleSubmit} className="qa-form">
          <div className="question-input-group">
            <textarea
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              placeholder="Ask a question about the Bible... (e.g., 'Where does the Bible talk about forgiveness?')"
              rows="3"
              disabled={loading}
              className="question-input"
            />
            <button
              type="submit"
              disabled={loading || !question.trim()}
              className="ask-button"
            >
              {loading ? 'Getting Answer...' : 'Ask Question'}
            </button>
          </div>

          {error && (
            <div className="error-message">
              <span className="error-icon">⚠️</span>
              {error}
            </div>
          )}
        </form>

        {/* Example Questions */}
        {!currentAnswer && history.length === 0 && (
          <div className="example-questions">
            <h3>Example Questions:</h3>
            <div className="example-grid">
              {exampleQuestions.map((example, index) => (
                <button
                  key={index}
                  onClick={() => handleExampleClick(example)}
                  className="example-button"
                  disabled={loading}
                >
                  {example}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Current Answer */}
        {currentAnswer && (
          <AnswerDisplay
            qa={currentAnswer}
            onFollowUpClick={handleFollowUpClick}
          />
        )}

        {/* History Toggle */}
        {history.length > 0 && (
          <div className="history-section">
            <button
              onClick={() => setShowHistory(!showHistory)}
              className="history-toggle"
            >
              {showHistory ? 'Hide' : 'Show'} Previous Questions ({history.length})
            </button>

            {showHistory && <QAHistory onQuestionClick={handleFollowUpClick} />}
          </div>
        )}

        {/* Loading Indicator */}
        {loading && (
          <div className="loading-indicator">
            <div className="spinner"></div>
            <p>Searching the scriptures and preparing your answer...</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default BibleQAPage;
